// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDegJtYR8gk7IBhREBDqlJY-AHbox4jvYk',
    appId: '1:1032544794357:android:0cf75546670b6b411bf7bc',
    messagingSenderId: '1032544794357',
    projectId: 'party-14e45',
    storageBucket: 'party-14e45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz9BK-P5GhBlJYyX7h51serZEwrksWT9I',
    appId: '1:1032544794357:ios:37e199c8ecb2479b1bf7bc',
    messagingSenderId: '1032544794357',
    projectId: 'party-14e45',
    storageBucket: 'party-14e45.appspot.com',
    iosClientId: '1032544794357-psitnsrldi83rk3htf5rufv2608vqo6h.apps.googleusercontent.com',
    iosBundleId: 'com.partymaker.app',
  );
}
